services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file: .env
    depends_on:
      - redis
    ports:
      - '8000:8000'

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: .env
    depends_on:
      - gateway
      - redis

volumes:
  redis_data:
